/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.10 at Mon Jun  3 14:49:02 2024. */

#ifndef PB_NACOS_GRPC_SERVICE_PB_H_INCLUDED
#define PB_NACOS_GRPC_SERVICE_PB_H_INCLUDED
#include <ngx_auto_headers.h>
#include <pb/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* Struct definitions */
typedef struct google_protobuf_Any {
    pb_callback_t type_url;
    pb_callback_t value;
    /* @@protoc_insertion_point(struct:google_protobuf_Any) */
} google_protobuf_Any;

/* Default values for struct fields */

/* Initializer values for message structs */
#define google_protobuf_Any_init_default \
    {                                    \
        {{NULL}, NULL}, { {NULL}, NULL } \
    }
#define google_protobuf_Any_init_zero    \
    {                                    \
        {{NULL}, NULL}, { {NULL}, NULL } \
    }

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_Any_type_url_tag 1
#define google_protobuf_Any_value_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t google_protobuf_Any_fields[3];

/* Struct definitions */
typedef struct Metadata {
    pb_callback_t type;
    pb_callback_t headers;
    pb_callback_t clientIp;
/* @@protoc_insertion_point(struct:Metadata) */
} Metadata;

typedef struct Metadata_HeadersEntry {
    pb_callback_t key;
    pb_callback_t value;
/* @@protoc_insertion_point(struct:Metadata_HeadersEntry) */
} Metadata_HeadersEntry;

typedef struct Payload {
    Metadata metadata;
    google_protobuf_Any body;
/* @@protoc_insertion_point(struct:Payload) */
} Payload;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Metadata_init_default                    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Metadata_HeadersEntry_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define Payload_init_default                     {Metadata_init_default, google_protobuf_Any_init_default}
#define Metadata_init_zero                       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Metadata_HeadersEntry_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define Payload_init_zero                        {Metadata_init_zero, google_protobuf_Any_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Metadata_type_tag                        3
#define Metadata_clientIp_tag                    8
#define Metadata_headers_tag                     7
#define Metadata_HeadersEntry_key_tag            1
#define Metadata_HeadersEntry_value_tag          2
#define Payload_metadata_tag                     2
#define Payload_body_tag                         3

/* Struct field encoding specification for nanopb */
extern const pb_field_t Metadata_fields[4];
extern const pb_field_t Metadata_HeadersEntry_fields[3];
extern const pb_field_t Payload_fields[3];

/* Maximum encoded size of messages (where known) */
/* Metadata_size depends on runtime parameters */
/* Metadata_HeadersEntry_size depends on runtime parameters */
/* Payload_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NACOS_GRPC_SERVICE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
