/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nacos_grpc_service.proto */

#ifndef PROTOBUF_C_nacos_5fgrpc_5fservice_2eproto__INCLUDED
#define PROTOBUF_C_nacos_5fgrpc_5fservice_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include <any.pb-c.h>

typedef struct Metadata Metadata;
typedef struct Metadata__HeadersEntry Metadata__HeadersEntry;
typedef struct Payload Payload;


/* --- enums --- */


/* --- messages --- */

struct Metadata__HeadersEntry {
    ProtobufCMessage base;
    char *key;
    char *value;
};
#define METADATA__HEADERS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&metadata__headers_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct Metadata {
    ProtobufCMessage base;
    char *type;
    char *clientip;
    size_t n_headers;
    Metadata__HeadersEntry **headers;
};
#define METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&metadata__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct Payload {
    ProtobufCMessage base;
    Metadata *metadata;
    Google__Protobuf__Any *body;
};
#define PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&payload__descriptor) \
    , NULL, NULL }


/* Metadata__HeadersEntry methods */
void metadata__headers_entry__init
        (Metadata__HeadersEntry *message);

/* Metadata methods */
void metadata__init
        (Metadata *message);

size_t metadata__get_packed_size
        (const Metadata *message);

size_t metadata__pack
        (const Metadata *message,
         uint8_t *out);

size_t metadata__pack_to_buffer
        (const Metadata *message,
         ProtobufCBuffer *buffer);

Metadata *
metadata__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data);

void metadata__free_unpacked
        (Metadata *message,
         ProtobufCAllocator *allocator);

/* Payload methods */
void payload__init
        (Payload *message);

size_t payload__get_packed_size
        (const Payload *message);

size_t payload__pack
        (const Payload *message,
         uint8_t *out);

size_t payload__pack_to_buffer
        (const Payload *message,
         ProtobufCBuffer *buffer);

Payload *
payload__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data);

void payload__free_unpacked
        (Payload *message,
         ProtobufCAllocator *allocator);

/* --- per-message closures --- */

typedef void (*Metadata__HeadersEntry_Closure)
        (const Metadata__HeadersEntry *message,
         void *closure_data);

typedef void (*Metadata_Closure)
        (const Metadata *message,
         void *closure_data);

typedef void (*Payload_Closure)
        (const Payload *message,
         void *closure_data);



/* --- descriptors --- */

extern const ProtobufCMessageDescriptor metadata__descriptor;
extern const ProtobufCMessageDescriptor metadata__headers_entry__descriptor;
extern const ProtobufCMessageDescriptor payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_nacos_5fgrpc_5fservice_2eproto__INCLUDED */
